"""Add user relationships to existing tables

Revision ID: 0b264938d458
Revises: a7fe55e3c43c
Create Date: 2025-06-30 21:43:00.355503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b264938d458'
down_revision: Union[str, None] = 'a7fe55e3c43c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns to characters table with batch mode
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_characters_created_by', 'users', ['created_by_id'], ['id'])

    # Add columns to conversations table with batch mode
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_conversations_user', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversations_user', type_='foreignkey')
        batch_op.drop_column('user_id')
        
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint('fk_characters_created_by', type_='foreignkey')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('is_public')
    # ### end Alembic commands ###
